pipes:
	@echo "Ejecutando cliserv2 con el fichero: prueba.txt"
	python3 cliserv2.py prueba.txt

binary:
	@echo "Ejecutando cliserv2 con el fichero: /bin/sh"
	python3 cliserv2.py /bin/sh

date:
	@echo "Ejecutando la hora con fechaHora.py"
	python3 fechaHora.py 


services:
	@echo "Ejecutando con fichero /etc/services"
	python3 cliserv2.py /etc/services

clean:
	@echo "Limpiando..."
