all:
	@echo "Ejecutando con fichero: "
	python3 serv6.py & cli6.py prueba.txt

binary:
	@echo "Ejecutando con fichero /bin/sh"
	python3 serv6.py & cli6.py /bin/sh

services:
	@echo "Ejecutando con fichero /etc/services"
	python3 serv6.py & cli6.py /etc/services

clean:
	@echo "Limpiando..."
